account/urls.py
from django.urls import path,include
from .views import SignUpView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('signup/' , SignUpView.as_view(),name='signup'),
    path('password_change/',include('django.contrib.auth.urls'),name='password_change'),
    path('password_reset/' , include('django.contrib.auth.urls'), name='password_reset'),

]

catalog/urls.py
from django.urls import path
from . import views
from django_filters.views import FilterView
from .filters import BookFilter

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('authers/', views.AuthersListView.as_view(), name='authers'),
    path('auther/<pk>/', views.AuthersDetailView.as_view(), name='auther-detail'),
    path('genre/', views.GenreListView.as_view(), name='genre'),
    path('genre/<pk>/', views.GenreDetailView.as_view(), name='genre-detail'),
    path('contact/', views.emailView, name='contact'),
    path('search/', FilterView.as_view(filterset_class=BookFilter,
                                       template_name='search/book_list_search.html'), name='search')
]

worldofbooks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

account/models.py
from django.db import models
from django.contrib.auth import models
# Create your models here.
# class CustomUser(models.AbstractUser):
#     age = models.DateField(null=True, blank=True )

catalog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.utils import timezone
# Create your models here.

# Start Table type of literature


class Genre(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Genre, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("genre-detail", args=[str(self.id)])
# End Table type of literature

# Start Table of authors


class Authers(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, null=True)
    img = models.ImageField(upload_to='auther_image/')
    date_of_publication = models.DateField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Authers, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-date_of_publication']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('auther-detail', args=[str(self.id)])
# End Table of authors

# Start Table of books


class Books(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(blank=True, null=True)
    cover = models.ImageField(upload_to='book_img/')
    pdf = models.FileField(upload_to='file_pdf/')
    summary = models.TextField()
    auther = models.ForeignKey(Authers, on_delete=models.SET_NULL, null=True)
    language = models.CharField(max_length=100)
    genre = models.ManyToManyField(Genre)
    date_of_publication = models.DateField(auto_now=True)
    famous_books = models.BooleanField(default=False)
    tags = models.CharField(max_length=300)

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
    display_genre.short_description = 'Genre'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Books, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-date_of_publication']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
# End Table of books

# Start Table of Team


class Team(models.Model):
    name = models.CharField(max_length=200)
    img = models.ImageField(upload_to='team_img/')
    specialty = models.CharField(max_length=300)

    def __str__(self):
        return self.name
# End Table of Team

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from .models import CustomUser

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,required=False)
    last_name = forms.CharField(max_length=100,required=False)
    email = forms.EmailField(help_text='Required. Inform a valid email address.')
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1','password2')

catalog/forms.py
from django import forms

class ContactForm(forms.Form):
    email      = forms.EmailField()
    subject    = forms.CharField(max_length=100)
    message    = forms.CharField(widget=forms.Textarea)
    # cc_myself  = forms.BooleanField(required=False)

account/views.py
from django.shortcuts import render
from .forms import SignUpForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

class SignUpView(CreateView):
    form_class    = SignUpForm
    success_url   = reverse_lazy('login')
    template_name = 'signup.html'

catalog/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Authers,Books,Team,Genre
from django.views.generic import ListView,DetailView
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ContactForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
def home(request):
    num_books   = Books.objects.all().count()
    num_authers = Authers.objects.all().count()
    books       = Books.objects.filter(famous_books=True)
    team        = Team.objects.all()
    context = {
        'num_books'   : num_books,
        'num_authers' : num_authers,
        'books'       : books,
        'team'        : team,
    }
    return render(request,'home.html',context)

class BookListView(ListView):
    model               = Books
    context_object_name = 'books_list'
    template_name       = 'catalog/books.html'
    paginate_by         = 32

class BookDetailView(LoginRequiredMixin,DetailView):
    model               = Books
    template_name       = 'catalog/book_detail.html'
    context_object_name = 'book'
    login_url           = 'login'

class AuthersListView(ListView):
    model               = Authers
    context_object_name = 'authers_list'
    template_name       = 'catalog/authers.html'
    paginate_by         = 32
    def Query_set(self):
        return Books.objects.filter(Authers=auther).count()

class AuthersDetailView(LoginRequiredMixin,DetailView):
    model               = Authers
    context_object_name = 'auther'
    template_name       = 'catalog/auther_detail.html'
    login_url           = 'login'

class GenreListView(ListView):
    model               = Genre
    context_object_name = 'genre_list'
    template_name       = 'catalog/genre.html'
    paginate_by         = 32
    def Query_set(self):
        return Books.objects.filter(Genre=genre).count()

class GenreDetailView(LoginRequiredMixin,DetailView):
    model               = Genre
    context_object_name = 'genre'
    template_name       = 'catalog/genre_detail.html'
    login_url           = 'login'

def emailView(request):
    if request.method == 'POST':
        form = ContactForm(request.POST or None)
        if form.is_valid():
            subject    = form.cleaned_data['subject']
            email      = form.cleaned_data['email']
            message    = form.cleaned_data['message']
            try:
                send_mail(subject+" - "+email, message, email,['worldofbooks1751998@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('home')
    else:
        form = ContactForm()
    return render(request, "contact.html", {'form': form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/24918.jpg' %}" title="world of books" />
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'colorlib/css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'colorlib/css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'colorlib/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'colorlib/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'colorlib/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'colorlib/css/c1.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/demoo.css' %}" />
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
    <link rel="stylesheet" href="{% static 'css.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
      <div class="container">
        <div class="logos">
          <img src="{% static 'img/Letter-W-Free-PNG-Image.png' %}" alt="le" class="potos" style="margin-top: -5px;margin-right: -12px;">
          <a class="navbar-brand" href="{% url 'home' %}" style="margin-top: -3px;font-weight: bolder;font-style: oblique;">orld OF Books</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-top: -7px;">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'books' %}">Books</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'authers' %}">Authors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'genre' %}">Genre</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <div class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="    border: 1px solid #27a289;border-radius: 11px;">
                {{ user.username }}
              </div>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user.is_staff  %}
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'search'%}">Search for your book</a>
                <a class="dropdown-item" href="{% url 'password_change'%}">password_change</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="    border: 1px solid #27a289;border-radius: 11px;">
                Login & SignUp
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'login' %}">Log In</a>
                <a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a>
              </div>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    {% block content %}

    {% endblock content %}
    {% block pagination %}

    {% endblock pagination%}
		<!-- Strat Footer Area -->
		<footer class="section-gap">
			<div class="container">
				<div class="footer-bottom d-flex justify-content-between align-items-center flex-wrap">
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					<p class="footer-text m-0">Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by M.A</p>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</div>
			</div>
		</footer>
		<!-- End Footer Area -->
    <script src="{% static 'js/java.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/catalog/auther_detail.html
{% extends 'base.html' %}
{% block title %}
{{book.title}}
{% endblock title %}
{% block content %}
<section class="banner-area relative" id="home">
  <div class="container">
    <h2 class="heading-two" style="margin-left: 40%;">
      {{auther.name}}
    </h2>
    <div class="row fullscreen align-items-center justify-content-center">
      <img src="{{auther.img.url}}" style="width: 25% ;margin-top: -50%;height:35%" class="img-thumbnail">
    </div>
    <div class="" style="margin-top: -50%;">
      <hr>
      {% for book in auther.books_set.all %}
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card">
          {% if book.cover %}
          <img style="width:100%" src="{{book.cover.url}}"/>
          {% endif %}
          <div class="card-content">
            <h4 class="card-title">
              {{book.title}}
            </h4>
            <div class="clearfix"></div>
          </div>
          <div class="card-read-more">
            <a href="{% url 'book-detail' book.slug %}" class="btn btn-link btn-block">
              Details
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

templates/catalog/authers.html
{% extends 'base.html' %}
{% block title %}
Authers
{% endblock title %}
{% block content %}
<section class="wrapper">
  <div class="container-fostrap">
    <div>
      <h1 class="heading" style="color: #000">
        World OF Books
      </h1>
      <h2 class="heading-two">
        Authors
      </h2>
    </div>
    <div class="content">
      <div class="container">
        <div class="row" style="margin-bottom: 25%">
          {% for author in authers_list %}
          <div class="col-xs-12 col-sm-4 col-md-3">
            <div class="card">
              {% if author.img %}
              <img style="width:100%;height: 270px;" src="{{author.img.url}}" class="img-thumbnail"/>
              {% endif %}
              <div class="card-content">
                <h4 class="card-title">
                  {{author.name}}
                </h4>
                <strong>Books</strong>
                <div class="col-lg-3 col-md-6 single-fact">
                  <h2 class="counter">{{author.books_set.count}}</h2>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="card-read-more">
                <a href="{% url 'auther-detail' author.slug %}" class="btn btn-link btn-block">
                  Details
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous </a>
    {% endif %}
    <span class="page-current">
      <p> | Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} | </p>
    </span>
    {% if page_obj.has_next %}
    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"> Next</a>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock content %}

templates/catalog/book_detail.html
{% extends 'base.html' %}
{% block title %}
{{book.title}}
{% endblock title %}
{% block content %}
<div class="container">
  <div class="component">
    <ul class="align">
      <li>
        <figure class='book' style="margin-bottom: 50%;">
          <!-- Front -->
          <ul class='hardcover_front'>
            <li>
              {% if book.cover %}<img src="{{book.cover.url}}" alt="ss" style="height:100%;width: 100%;">{% endif %}
            </li>
            <li></li>
          </ul>
          <!-- Pages -->
          <ul class='page'>
            <li></li>
            <li>
              <a class="btnn" href="{{book.pdf.url}}">Download</a>
            </li>
            <li></li>
            <li></li>
            <li></li>
          </ul>
          <!-- Back -->
          <ul class='hardcover_back'>
            <li></li>
            <li></li>
          </ul>
          <ul class='book_spine'>
            <li></li>
            <li></li>
          </ul>
          <figcaption>
            <h1>{{book.title}}</h1>
            <a href="{% url 'auther-detail' book.auther.slug %}"><span>{{book.auther.name}}</span></a>
            <p>{{book.summary}}.</p>
          </figcaption>
        </figure>
      </li>
    </ul>
  </div>
</div>
{% endblock content %}

templates/catalog/books.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Books
{% endblock title %}
{% block content %}
<section class="wrapper">
  <div class="container-fostrap">
    <div>
      <h1 class="heading" style="color: #000">
        World OF Books
      </h1>
      <h2 class="heading-two">
        Books
      </h2>
<br><br>
  </div>
  <div class="content">
    <div class="container">
      <div class="row" style="margin-bottom: 25%">
        {% for book in books_list %}
        <div class="col-xs-12 col-sm-4 col-md-3">
          <div class="card">
            {% if book.cover %}
            <img style="width:100%" src="{{book.cover.url}}"/>
            {% endif %}
            <div class="card-content">
              <h4 class="card-title">
                {{book.title}}
              </h4>
              <div class="text-danger pull-left">
                {% if book.auther.img %}
                <img style="width:15%" class="img-fluid" src="{{book.auther.img.url}}" alt="">
                {% endif %}
                <a href="{{ book.auther.get_absolute_url }}">{{book.auther.name}}</a>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="card-read-more">
              <a href="{{ book.get_absolute_url }}" class="btn btn-link btn-block">
                Details
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous </a>
    {% endif %}
    <span class="page-current">
      <p> | Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} | </p>
    </span>
    {% if page_obj.has_next %}
    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"> Next</a>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock content %}

templates/catalog/genre.html
{% extends 'base.html' %}
{% block title %}
genre
{% endblock title %}
{% block welcome %}Genre{% endblock welcome %}
{% block content %}
<!-- Start blog Area -->
<section class="wrapper">
  <div class="container-fostrap">
    <div>
      <h1 class="heading" style="color: #000">
        World OF Books
      </h1>
      <h2 class="heading-two">
        Genre
      </h2>
    </div>
    <div class="content">
      <div class="container">
        <div class="row">
          {% for genre in genre_list %}
          <div class="col-xs-12 col-sm-4 col-md-3">
            <div class="card">
              <div class="card-content">
                <h4 class="card-title python-tag">
                  <a href="{% url 'genre-detail' genre.slug %}">{{genre.name}}</a>
                </h4>
                <div class="clearfix"></div>
              </div>
              <h2 class="counter card-read-more">{{genre.books_set.count}}</h2>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
</section>
{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous </a>
    {% endif %}
    <span class="page-current">
      <p> | Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} | </p>
    </span>
    {% if page_obj.has_next %}
    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"> Next</a>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock content %}

templates/catalog/genre_detail.html
{% extends 'base.html' %}
{% block title %}
{{genre.name}}
{% endblock title %}
{% block welcome %}{{genre.name}}{% endblock welcome %}
{% block content %}
<section class="wrapper">
  <div class="container-fostrap">
    <div>
      <h1 class="heading" style="color: #000">
        World OF Books
      </h1>
      <h2 class="heading-two">
        {{genre.name}}
      </h2>
    </div>
    <div class="content">
      <div class="container">
        <div class="row" style="margin-bottom: 25%">
          {% for book in genre.books_set.all %}
          <div class="col-xs-12 col-sm-4 col-md-3">
            <div class="card">
              {% if book.cover %}
              <img style="width:100%" src="{{book.cover.url}}"/>
                {% endif %}
                <div class="card-content">
                  <h4 class="card-title">
                    {{book.title}}
                  </h4>
                  <div class="text-danger pull-left">
                    {% if book.auther.img %}
                    <img style="width:15%" class="img-fluid" src="{{book.auther.img.url}}" alt="">
                    {% endif %}
                    <a href="{% url 'auther-detail' book.auther.slug %}">{{book.auther.name}}</a>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="card-read-more">
                  <a href="{% url 'book-detail' book.slug %}" class="btn btn-link btn-block">
                    Details
                  </a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
  contact
{% endblock title %}
{% block content %}
<section class="wrapper">
  <div class="container-fostrap">
    <div>
      <h1 class="heading" style="color: #000">
        World OF Books
      </h1>
      <h2 class="heading-two">
        CONTACT WITH US
      </h2>
    </div>
    <footer>
      <div id="footer"  style="margin-bottom: 0%;">
        
        <div class="col-xs-12 col-md-12">
          <form id="contact-form" method="POST" class="contact-form">{% csrf_token %}
            <div class="forming" style="margin-left: 10%;margin-right: 10%;">
              {% bootstrap_form form %}
              {% buttons %}
              <button type="submit" class="btn btn-primary">Sibmit</button>
              {% endbuttons %}
            </div>
          </form>
        </div>
      </div>
    </footer>
  </div>
</section>
{% endblock content %}

templates/home.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
world of books
{% endblock title %}
{%block content%}
<header>
  <div class="headering">
    <div class="backing">
      <div class="container">
        <h2>Welcome To World Of Books</h2>
      </div>
    </div>
  </div>
</header>
<!-- Start Header -->
<div class="smail-cont" style="background-color: #e2e2e2;    border-top: 4px solid;border-bottom: 2px solid;">
  <img src="{% static 'img/2085674.jpg' %}" alt="aa" width="40%" height="450px">
  <h2>World OF Books<br>Everything you want and more </h2>
</div>
<!-- End Header -->
<section class="wrapper">
  <div class="container-fostrap">
    <div>
      <h1 class="heading" style="color: #000">
        World OF Books
      </h1>
    </div>
  </div>
</section>
<!-- Start fact Area -->
<section class="facts-area pt-100 pb-100">
  <div class="container">
    <div class="row" style="margin-left: 30%;">
      <div class="col-lg-3 col-md-6 single-fact">
        <h2 class="counter">{{num_books}}</h2>
        <p class="text-uppercase">Books</p>
      </div>
      <div class="col-lg-3 col-md-6 single-fact">
        <h2 class="counter">{{num_authers}}</h2>
        <p class="text-uppercase">Authors</p>
      </div>
    </div>
  </div>
</section>
<!-- end fact Area -->
<!-- End famous_book area -->
<section class="wrapper">
  <div class="container-fostrap">
    <div class="content">
      <div class="container">
        <h2 class="heading-two">
          The most famous books
        </h2>
        <div class="row">
          {% for famous_book in books %}
          <div class="col-xs-12 col-sm-4 col-md-3">
            <div class="card">
              {% if famous_book.cover %}
              <img style="width:100%" src="{{famous_book.cover.url}}"/>
              {% endif %}
              <div class="card-content">
                <h4 class="card-title">
                  {{famous_book.title}}
                </h4>
                <div class="text-danger pull-left">
                  {% if famous_book.auther.img %}
                  <img style="width:15%" class="img-fluid" src="{{famous_book.auther.img.url}}" alt="">
                  {% endif %}
                  <a href="{% url 'auther-detail' famous_book.auther.id %}">{{famous_book.auther.name}}</a>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="card-read-more">
                <a href="{% url 'book-detail' famous_book.id %}" class="btn btn-link btn-block">
                  View Book
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<br>
<!-- End famous_book area -->

{% endblock%}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<section class="wrapper">
  <div class="container-fostrap">
    <div>
      <h1 class="heading" style="color: #000">
        World OF Books
      </h1>
      <h2 class="heading-two">
        Sign Up
      </h2>
    </div>
    <div id="formWrapper">
      <div id="form">
        <form method="POST" style="margin-left:30%; margin-top:0;margin-right:30%;margin-bottom:0">{% csrf_token %}
          <img src="{% static 'img/ssss2195406.jpg' %}" alt="aa" style="    width: 100%;">
          {% bootstrap_form form %}
          {% buttons %}
          <button type="submit" class="btn btn-primary">Sign Up</button>
          {% endbuttons %}
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}